language: de

pipeline:
- name: "SpacyNLP"
  model: "de_core_news_sm"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
  # Text will be processed with case sensitive as default
  "case_sensitive": False
  # use match word boundaries for lookup table
  "use_word_boundaries": True
- name: "SpacyFeaturizer"
  "pooling": "mean"
- name: "SklearnIntentClassifier"
- name: "CRFEntityExtractor"

policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#   - name: RulePolicy
